name = "TutorialZH"
uuid = "4d0b14d6-8fbb-11e8-1bfb-818095dff5f7"
authors = ["Roger-luo <hiroger@qq.com>"]
version = "0.1.0"

[deps]
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
